package vu.mif.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;
import vu.mif.mybatis.model.EmployeeProject;

@Mapper
public interface EmployeeProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE_PROJECT
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    int deleteByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("projectId") Integer projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE_PROJECT
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    int insert(EmployeeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EMPLOYEE_PROJECT
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    List<EmployeeProject> selectAll();
}