package vu.mif.mybatis.model;

public class EmployeeProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE_PROJECT.EMPLOYEE_ID
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE_PROJECT.PROJECT_ID
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE_PROJECT.EMPLOYEE_ID
     *
     * @return the value of PUBLIC.EMPLOYEE_PROJECT.EMPLOYEE_ID
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE_PROJECT.EMPLOYEE_ID
     *
     * @param employeeId the value for PUBLIC.EMPLOYEE_PROJECT.EMPLOYEE_ID
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE_PROJECT.PROJECT_ID
     *
     * @return the value of PUBLIC.EMPLOYEE_PROJECT.PROJECT_ID
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE_PROJECT.PROJECT_ID
     *
     * @param projectId the value for PUBLIC.EMPLOYEE_PROJECT.PROJECT_ID
     *
     * @mbg.generated Mon Apr 22 13:32:54 EEST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}