package vu.mif.mybatis.model;

import java.math.BigDecimal;
import java.util.List;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.FIRSTNAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.LASTNAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private BigDecimal salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @return the value of PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.ID
     *
     * @param id the value for PUBLIC.EMPLOYEE.ID
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.FIRSTNAME
     *
     * @return the value of PUBLIC.EMPLOYEE.FIRSTNAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.EMPLOYEE.FIRSTNAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.LASTNAME
     *
     * @return the value of PUBLIC.EMPLOYEE.LASTNAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.LASTNAME
     *
     * @param lastname the value for PUBLIC.EMPLOYEE.LASTNAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @return the value of PUBLIC.EMPLOYEE.SALARY
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE.SALARY
     *
     * @param salary the value for PUBLIC.EMPLOYEE.SALARY
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    private List<Project> projects;

    public void setProjects(List<Project> projects) {this.projects = projects; }
    public List<Project> getProjects() {return this.projects; }

    @Override
    public String toString() {
        return this.getFirstname() + ' ' + this.getLastname();
    }
}