package vu.mif.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.ID
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.STARTDATE
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.WORTH
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    private BigDecimal worth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.ID
     *
     * @return the value of PUBLIC.PROJECT.ID
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.ID
     *
     * @param id the value for PUBLIC.PROJECT.ID
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.NAME
     *
     * @return the value of PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.NAME
     *
     * @param name the value for PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.STARTDATE
     *
     * @return the value of PUBLIC.PROJECT.STARTDATE
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.STARTDATE
     *
     * @param startdate the value for PUBLIC.PROJECT.STARTDATE
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.WORTH
     *
     * @return the value of PUBLIC.PROJECT.WORTH
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public BigDecimal getWorth() {
        return worth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.WORTH
     *
     * @param worth the value for PUBLIC.PROJECT.WORTH
     *
     * @mbg.generated Sun Apr 21 21:43:32 EEST 2019
     */
    public void setWorth(BigDecimal worth) {
        this.worth = worth;
    }

    private List<Stage> stages;

    public List<Stage> getStages() { return this.stages; }

    public void setStages(List<Stage> stages) {
        this.stages = stages;
    }

    private List<Employee> employees;

    public List<Employee> getEmployees() { return this.employees; }

    public void setEmployees(List<Employee> employees) {
        this.employees = employees;
    }
}